### ISSUE TITLE
Expose the base URL parameter in the Google connector

### ISSUE THREAD

**Issue by stsmork** [asgeirf/okapi#1]
Google's Neural MT service uses a different URL than the base URL hard-coded in net.sf.okapi.connectors.google.GoogleMTv2Connector

**Comment by asgeirf** [comment]
Hi @stsmork, the main repository for okapi is hosted at:

https://bitbucket.org/okapiframework/okapi/

You might want to raise an issue there.

**Comment by stsmork** [comment]
Will do! -- Peter
